
find_path(WEBP_INCLUDE_DIR NAMES png.h PATHS ${CONAN_INCLUDE_DIRS_LIBWEBP} NO_CMAKE_FIND_ROOT_PATH)
find_library(WEBP_LIBRARY NAMES ${CONAN_LIBS_LIBWEBP} PATHS ${CONAN_LIB_DIRS_LIBWEBP} NO_CMAKE_FIND_ROOT_PATH)

MESSAGE("** WEBP ALREADY FOUND BY CONAN!")
SET(WEBP_FOUND TRUE)
MESSAGE("** FOUND WEBP:  ${WEBP_LIBRARY}")
MESSAGE("** FOUND WEBP INCLUDE:  ${WEBP_INCLUDE_DIR}")

set(PNG_INCLUDE_DIRS ${WEBP_INCLUDE_DIR})
set(PNG_LIBRARIES ${WEBP_LIBRARY})

mark_as_advanced(WEBP_LIBRARY WEBP_INCLUDE_DIR)


set(WEBP_MAJOR_VERSION "0")
set(WEBP_MINOR_VERSION "6")
set(WEBP_PATCH_VERSION "0")
